steps:
  - label: "Buildkite Basic Test"
    command: |
      echo =====================================
      echo   Buildkite CI is Working Successfully
      echo =====================================
      echo.
      echo Listing project files:
      dir
    agents:
      queue: "windows"