steps:
  - label: "Build Static Site"
    command: |
      echo "Running Buildkite Build"
      mkdir output
      xcopy index.html output\ /Y
    agents:
      queue: "windows"

  - label: "List Output"
    command: "dir output"
    agents:
      queue: "windows"